title: Dávid Kovács
email: dadikovi@gmail.com
site:
  url: http://dadikovi.github.io
  baseurl: ""

# Build settings
theme: minima
paginate: 10
paginate_path: "/blog/page/:num"
permalink: /:categories/:title:output_ext
plugins:
  - jekyll-feed
