title: Dávid Kovács
email: dadikovi@gmail.com
description: Java Developer
site:
  url: http://dadikovi.github.io
  baseurl: ""

# Build settings
theme: minima
paginate: 3
paginate_path: "/blog/page/:num"
plugins:
  - jekyll-feed
